FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# AdritaAlam 


Base Url 
http://localhost:3000/api/

Endpoints
/cats
The server will response with all the details about the cats those are stored in the daatabase(MongoDB).
 
/cats/{catId}
The server will response with the information for the id that have requested,to the server

And, for Four operations the server will response for 

gets: Read the items stored on the database
put : Update the stored data with another data
post: Create a data to store in the database
delete: Delete the stored data

And,here mongodb schema and model are used to store data for cats api.